project:
  type: website

website:
  title: 'ResBaz Arizona'
  navbar:
    background: dark
    foreground: primary
    left:
      - href: index.qmd
        text: Home
      - href: index.qmd#events
        text: Events
      # - href: whoWeAre.qmd
      #  text: Who We Are
  body-footer: |
    ::: {.footer}
      ![ResBaz Logo](/img/logos/ResBazAZrectanglelogo-small.png) \
      [Code of Conduct](https://github.com/resbazaz/organization/blob/main/GOVERNANCE.md#code-of-conduct)
    :::

format:
  html:
    theme:
      - none
      - theme.scss
    resources:
      - styles
      - img
      - data
    toc: true
