---
layout: default
title: ResBaz Arizona
css: /styles/festivalPages.css
aliases:
  - resbazArizona2026
  - resbazTucson2026
  - /2026
---

```{=html}
<script type="text/javascript" src="https://latest.cactus.chat/cactus.js"></script>
```

<link rel="stylesheet" href="https://latest.cactus.chat/style.css" type="text/css">

The Research Bazaar is a worldwide festival promoting the digital literacy emerging at the center of modern research. Throughout 2026, events are happening at university campuses around the globe.

ResBaz Arizona is a free festival happening **May 14–16 2026** where researchers and community members come together to up-skill in "next generation digital research tools and skills." In the spirit of a marketplace or bazaar, ResBaz is a highly participatory event where researchers from many different disciplines can learn, share knowledge and skills, and have fun!

**Who should attend?** Faculty, students, and science enthusiasts from any (or no) research organization are welcome. PhD and research master's students are especially encouraged to attend. Research technologists who support researchers to do their job should also come along!

### 2026 Theme: Do Your Own Research

*When dealing with potential AI hallucinations, errors, or misinformation, **how are your fact-checking skills?***

### General schedule

+----------------------+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Date                 | Time          |                                                                                                                                                                   |
+======================+===============+===================================================================================================================================================================+
| **Thursday, May 14** | **4:00–6:00** | [**Hacky Hour**](/index.qmd#hacky-hour)                                                                                                                           |
|                      |               |                                                                                                                                                                   |
|                      |               | Snakes & Lattes\                                                                                                                                                  |
|                      |               | 988 E University Blvd, Tucson, AZ ([map](https://www.openstreetmap.org/node/13062971951))                                                                         |
|                      |               |                                                                                                                                                                   |
|                      |               | Special kick-off of our regular weekly event                                                                                                                      |
+----------------------+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Friday, May 15       | 9:00–9:30     | Welcome                                                                                                                                                           |
+----------------------+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                      | 9:30–10:30    | Expert Panel: What does "rigor" mean? How do you go about checking for it?                                                                                        |
+----------------------+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                      | 10:30–12:00   | Unconference Bazaar: Lightning talks & Birds of a Feather                                                                                                         |
+----------------------+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                      | 12:00–2:00    | Lunch break                                                                                                                                                       |
+----------------------+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                      | 2:00–4:00     | [Catalyst Maker Studio](https://lib.arizona.edu/study/spaces/maker-studio) tour & fact-checking / literature review scavenger hunt deep into the library's stacks |
+----------------------+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                      | 4:00–5:00     | Regroup to share discoveries                                                                                                                                      |
+----------------------+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Saturday, May 16     | 9:00–5:00     | Help-a-thon: get hands-on research experience with data and code, and/or bring your own research project!                                                         |
+----------------------+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Accessibility

We are committed to making this workshop accessible to everybody. For any accommodation requests, please contact us at [ResBazAZ+JEDI\@gmail.com](mailto:ResBazAZ+JEDI@gmail.com){.email}. We will do our best to make the event inclusive to all.

## Previous years

-   [ResBaz Tucson 2025](/resbaz/resbazTucson2025.qmd)
-   [ResBaz Tucson 2024](/resbaz/resbazTucson2024.qmd)
-   [ResBaz Arizona 2023](/resbaz/Arizona2023.qmd)
-   [ResBaz Tucson 2022](/resbaz/resbazTucson2022.qmd)
-   [ResBaz Tucson 2021](/resbaz/resbazTucson2021.qmd)
-   [ResBaz Tucson 2020](/resbaz/resbazTucson2020.qmd)
-   [ResBaz Tucson 2019](/resbaz/resbazTucson2019.qmd)
-   [ResBaz Tucson 2018](/resbaz/resbazTucson2018.qmd)

```{=html}
<!--
## Comments

<div id="comment-section"></div>

<script>
initComments({
  node: document.getElementById("comment-section"),
  defaultHomeserverUrl: "https://matrix.cactus.chat:8448",
  serverName: "cactus.chat",
  siteName: "resbazaz",
  commentSectionId: "festival2025",
  updateInterval: 15,
  loginEnabled: true,
  guestPostingEnabled: true,
  pageSize: 6
})
</script>
-->
```