---
layout: default
title: ResBaz Arizona
aliases:
  - resbazArizona2024 
---

The Research Bazaar is a worldwide festival promoting the digital literacy emerging at the center of modern research. Throughout 2024, events are happening at university campuses around the globe.

ResBaz Arizona is a free, multi-day intensive conference happening **May 15th - 17th 2024** where researchers come together to up-skill in "next generation digital research tools and skills." In the spirit of a marketplace or bazaar, ResBaz is a highly participatory event where researchers from many different disciplines can learn, share knowledge and skills, and have fun!

Who should attend? Researchers at ALL levels from ALL disciplines. PhD and research master's students are especially encouraged to attend. Research technologists who support researchers to do their job should also come along!

[Register here!](https://forms.gle/u5naq46pn3YoKERd8)

### How do I participate in ResBaz?

At ResBaz, you choose your level of participation. 

All in? On the [event registration link](https://forms.gle/u5naq46pn3YoKERd8), you will find a choice to volunteer to be contacted to speak, help, or facilitate a session. 

Just starting out? Join us for one session, one day, or the entire conference, depending on your interests and availability. 

### What can I do at ResBaz?

Learn, Network, Teach, Help, and Discuss are just a few of the availble things to do at ResBaz. Use the conference to add organizing events to your resume or simply attend and pick up a new data science trick, the choice is all yours!

## Schedule

*Calendar coming soon!*

* Wednesday, 15th May: fully online conference day
* Thursday, 16th May: in-person day & Social
* Friday, 17th May: in-person day

## Where to participate

*Map(s) and Zoom links coming soon!*

#### Accessibility

We are committed to making this workshop accessible to everybody. For any accommodation requests, please contact us at <ResBazAZ+JEDI@gmail.com>. We will do our best to make the event inclusive to all. 

## Previous years

- [ResBaz Arizona 2023](/resbaz/Arizona2023.qmd)
- [ResBaz Tucson 2022](/resbaz/resbazTucson2022.qmd)
- [ResBaz Tucson 2021](/resbaz/resbazTucson2021.qmd)
- [ResBaz Tucson 2020](/resbaz/resbazTucson2020.qmd)
- [ResBaz Tucson 2019](/resbaz/resbazTucson2019.qmd)
